name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, World!

      - name: Run a mulyi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
